### PR TITLE
Fix #6857: undefined max

### LINKED ISSUE #6857: cloudmc UI error with "Zero Power Reactor Experiment" sim
On dev I am seeing: `Application Error: TypeError: Cannot set properties of undefined (setting 'max'). A report was sent to the server.`

### PR DESCRIPTION
**Pull request by gurhar1133**

### CODE REVIEW

File: sirepo/package_data/static/js/cloudmc.js [hunk 1]
```diff
@@ -2601,7 +2601,7 @@ SIREPO.app.directive('jRangeSlider', function(appState, panelState) {
         `,
         controller: function($scope, $element) {
             $scope.appState = appState;
-            $scope.sliderClass = `${$scope.modelName}-${$scope.fieldName}-slider`;
+            $scope.sliderClass = `${$scope.modelName}-${$scope.fieldName}-slider`.replace(/ /g, "-");
```
Comment (mkeilman) [inline sirepo/package_data/static/js/cloudmc.js:2604]: single quotes

**Review by mkeilman — APPROVED** [review]
Change the double to single quotes and you're good to merge
