### PR TITLE
fix #5632 silas improvements

### LINKED ISSUE #5632: list of silas changes
- [x] allow stepping through the pulse slices (intensity and phase) using the play/step buttons
- [x] intensity plots should have a "sum of all slices" option in addition to slice-by-slice
```python
# example of intensity for full pulse
e_total = LaserPulse.extract_total_2d_elec_fields()
intensity = 0.5 *const.c *const.epsilon_0 *(e_total.re**2.0 + e_total.im**2.0)

fig = plt.figure()
ax = fig.gca()
plt.pcolormesh(x*(1e3), y*(1e3), intensity, cmap=plt.cm.viridis, shading='auto')
plt.colorbar()
ax.set_ylabel(r'Vertical Position [mm]')
ax.set_xlabel(r'Horizontal Position [mm]')
ax.set_title('Intensity')
```

- [x] phase results should be unwrapped 
```python
phase_plot = np.unwrap(np.unwrap(phase,axis=0),axis=1)
```

**Laser Pulse**
- [x] remove gauss-hermite mode order fields
- [x] gaussian polarization should have only one available option "Linear Horizontal" 
- [x] remove pad factor field
- [x] when "From Files" distribution is selected, the fields should be named this, and in this order
> - CCD --> Intensity
> - WaveFronts --> Phase
> - Meta --> WFS Space Data
>   add help text for WFS file: A file describing the pixel dimensions of your wavefront sensor. Pixel dimensions are assumed to be in microns.
- [x] number of points in mesh should default to 64x64 (not 500x500)
- [x] Rename Distribution tab --> Transverse
- [x] Rename Geometry tab --> Longitudinal
- [x] Move Number of Gaussian Sigmas fields to separate tabs

**Crystal beamline element**
 - [x]  remove "diffusion constant" field
 - [x]  move Number of Slices to the crystal Geometry tab
 - [x]  rename Index of Refraction to "Index of Refraction (n0)"
 - [x]  Thermal Lensing (n2) label
 - [x]  For each crystal show a plot with the "population of excited states" created at the exit from each crystal
 - [x]  One crystal element may be reused - when adding a crystal give the option to select an existing one from the beamline, or "new"
 - [x]  Add "Laser gain" boolean to crystal. If enabled show 6 more fields.
```python
# Where gain and radial_n2 are flags. gain turns on the gain during the propagation. Radial_n2 is the transverse variation toggle. 
LaserPulse = e_crystal.propagate(LaserPulse, prop_type, gain, radial_n2)
```
```python
# To look at the mesh of excited states you need to plot
# crystal.slice[i].pop_inversion_mesh  which represents num_excited_states/m^3. The x and y are currently defined by # pop_inversion_nx, pop_inversion_xstart, pop_inversion_xfin, etc.

# To set the mesh of excited states, the user can set the params of
    inversion_n_cells = 64,
    inversion_mesh_extent = 0.01, # [m]
    crystal_alpha   = 120.0,      # [1/m], 1.2 1/cm
    pump_waist      = 0.00164,  # [m]
    pump_wavelength = 532.0e-9, # [m]
    pump_energy = 0.0211, #[J]
```
- [x] see test_pulse_init.ipynb
- [x] rename crystal Gain tab to "Laser Gain"
- [x] rename "Include Transverse Variation" to "Transverse Variation of Thermal Lensing"
- [x] Only show these propagation types ABCD, Gain Calculation, N0N2 SRW, N0N2 LCT
- [x] If "Gain Calculation" propagator is selected, hide n2 and other unused fields for that propagator
- [x] see single_crystal_pass.ipynb shows an example of using the  thisPulse.extract_total_2d_phase() function to pull out the weighted average of the phase for the full laser pulse
- [x] plots for longitudinal distribution at watchpoints
- [x] create example sim from the experimental_comparison.ipynb

Top-level Crystal tab
- [x] rename the main Crystal tab to "Thermal

### LINKED ISSUE #5786: longitudinal plot for laser pulse watchpoint

### LINKED ISSUE #5794: Longitudinal plot for pulse intensity

### LINKED ISSUE #5795: Total intensity plot
we need a “total intensity” heatmap plot. In the notebooks there is some call which converts all the pulse slices into one heatmap. We want to save that as a new entry in the h5 file, and add a new plotType for “total intensity” to display it

### LINKED ISSUE #5797: bad axis format for large range parameter plots
The plot is incorrectly displayed as this:
x
when it should be this:
x2

### LINKED ISSUE #5802: unwrap phase plots for silas beamline

### LINKED ISSUE #5805: create silas example sim from notebook
use the experimental_comparison.ipynb notebook

### PR DESCRIPTION
**Pull request by moellep**
- fix #5797 fix bad axis labels and added more test cases
- fix #5805 adds silas experimental comparison example
- fix #5802 unwrap phase data
- fix #5795 added total intensity plot
- fix #5794 added longitudinal intensity plot
- fix #5786 longitudinal intensity plot at watchpoint
- fix #5632 remaining silas items

### CODE REVIEW

File: sirepo/package_data/static/js/silas.js [hunk 1]
```diff
@@ -42,7 +41,10 @@ SIREPO.app.factory('silasService', function(appState) {
         if (['crystalAnimation', 'crystal3dAnimation', 'plotAnimation', 'plot2Animation'].indexOf(analysisModel) >= 0) {
             return 'crystalAnimation';
         }
-        return 'animation';
+        if (analysisModel === 'laserPulseAnimation' || analysisModel == 'laserPulse2Animation') {
```
Comment (gurhar1133) [inline sirepo/package_data/static/js/silas.js:44]: maybe
```javascript
if (['laserPulseAnimation', 'laserPulse2Animation'].includes(analysisMode)) { ...
```

File: sirepo/template/silas.py [hunk 2]
```diff
@@ -38,64 +31,64 @@ def background_percent_complete(report, run_dir, is_running):
...
-        _extract_watchpoint_report(run_dir, sim_in)
+def sim_frame(frame_args):
+    r = frame_args.frameReport
+    frame_args.sim_in.report = r
+    count, element = _report_to_file_index(frame_args.sim_in, r)
+    if "beamlineAnimation" in r or r in _SIM_DATA.SOURCE_REPORTS:
+        return _laser_pulse_plot(
+            frame_args.run_dir,
+            frame_args.crystalPlot
+            if element and element.type == "crystal"
```
Comment (gurhar1133) [inline sirepo/template/silas.py:84]: maybe replace if/else with small function

File: sirepo/template/silas.py [hunk 3]
```diff
@@ -135,6 +130,68 @@ def write_parameters(data, run_dir, is_parallel):
...
 
+def _beamline_animation_percent_complete(run_dir, res, data):
+    _initial_intensity_percent_complete(run_dir, res, data, ("beamlineAnimation0",))
+    count = PKDict(
+        watch=1,
+        crystal=1,
+    )
+    total_count = 1
+    for e in data.models.beamline:
+        if e.type == "watch":
```
Comment (gurhar1133) [inline sirepo/template/silas.py:141]: A decent amount of repetition here. Could be something like
```python
PKDict(
    watch=_output_append(...),
    crystal=_output_append(...),
    
)[e.type](...)

def _output_append(...):
    if run_dir.join(_RESULTS_FILE.format(count.watch)).exists():
                res.outputInfo.append(
                    PKDict(
                        modelKey="beamlineAnimation{}".format(e.id),
                        filename=_RESULTS_FILE.format(count.watch),
                        id=e.id,
                        frameCount=data.models.laserPulse.nslice,
                    )
                )
```

**Review by gurhar1133 — COMMENTED** [review]
Runs well. Left some potential refactoring suggestions. Willing to do the refactoring if you like @moellep

File: sirepo/template/silas.py [hunk 4]
```diff
@@ -38,64 +31,64 @@ def background_percent_complete(report, run_dir, is_running):
...
+    return _parse_silas_log(run_dir)
+
+
 def python_source_for_model(data, model, qcall, **kwargs):
     if model in ("crystal3dAnimation", "plotAnimation", "plot2Animation"):
         data.report = "crystalAnimation"
     else:
-        data.report = model or _last_watchpoint(data) or "initialIntensityReport"
+        if model:
+            model = re.sub("beamlineAnimation", "watchpointReport", model)
```
[the remark this answers is not in the document]
Comment (moellep) [reply sirepo/template/silas.py:71]: I think the beamline logic was originally dealing with watchpointReport, but then SRW was changed to run as an animation, and silas also runs as an animation. You can try removing this, but I think when you select python-source on the plots, it may require this.

**Comment by moellep** [comment]
Yes, @gurhar1133 please update the branch with those refactors.

File: sirepo/package_data/template/silas/parameters.py.jinja [hunk 5]
```diff
@@ -15,6 +16,58 @@ class Mirror:
...
+                (pulse.slice_wfr(0).mesh.ny, pulse.slice_wfr(0).mesh.nx),
+            )
+
+        def ranges(pulse, idx):
+            return laser_pulse_ranges(pulse.slice_wfr(idx))
+
+        h5_data = PKDict()
+        lp = locals()["pulse"]
+        t = lp.extract_total_2d_elec_fields()
+        p = lp.extract_total_2d_phase()
```
[the remark this answers is not in the document]
Comment (gurhar1133) [reply sirepo/package_data/template/silas/parameters.py.jinja:52]: nvm `p` makes sense

**Comment by gurhar1133** [comment]
@moellep did those refactors.
