### PR TITLE
Fix #3981 blicon ml tabulated und fails

### LINKED ISSUE #3981: blicon: SRW ML data generator with tabulated undulator
The "export ML script" feature works OK for idealized undulator simulations, but fails with a "Magnetic Field is not defined" for simulations which use a tabulated undulator.

To reproduce, use the Export ML script with the "NSLS-II CHX beamline (tabulated)" simulation.

### PR DESCRIPTION
**Pull request by mkeilman**
Tabulated undulators are only "activated" when a ```plot_reports``` param is true. We don't want to produce plots as part of the rsopt runs (at least by default) so this adds a check for rsopt runs in the appropriate places.

Also cleans up the readme and shell script

### CODE REVIEW

File: sirepo/package_data/template/srw/rsoptExport.sh.jinja [hunk 1]
```diff
@@ -14,8 +14,13 @@ then
     if [[ $confirm == [yY] ]]; then
         echo Running SRW...
         eval "$run_py"
-        echo Propagated single electron intensities are in datasets/beam_intensities.npy
-        echo Corresponding parameter values are in datasets/parameters.npy
+        if [ $? -eq 0 ]
```
Comment (e-carlin) [inline sirepo/package_data/template/srw/rsoptExport.sh.jinja:17]: I think this can be simplified to
```bash
if eval "run_py"; then
...
else
...
fi
```

File: sirepo/template/srw.py [hunk 2]
```diff
@@ -1991,6 +1993,7 @@ def _set_magnetic_measurement_parameters(run_dir, v):
 
 def _set_parameters(v, data, plot_reports, run_dir):
     report = data.report
+    for_rsopt = report == 'rsoptExport'
```
Comment (e-carlin) [inline sirepo/template/srw.py:1996]: May be clearer to make this a function since it is used across functions.

**Comment by mkeilman** [comment]
I was just working on the comments :). I will incorporate them into the next pr

**Comment by moellep** [comment]
Yes, I thought this was good enough for the alpha release today.
