### PR TITLE
Fix #4448: undulator length auto updates

### LINKED ISSUE #4448: updating idealized undulator length should update beam drift
In SRW when you edit the Length of an Idealized Undulator, it should update the Electron Beam Drift if the beam's "Drift Calculation Method" is set to Automatic.

For example, if you select the "NSLS-II CHX beamline" example, and change the Idealized Undulator Length to 3.1, the Single-Electron Spectrum report is all wrong:
Single-Electron-Spectrum-20-5m

If you edit the Electorn Beam, and then toggle the Drift Calculation Method between Automatic and Manual, the value changes from -1.54 to the correct value -1.59 and the Single-Electron Spectrum now looks correct again:

Single-Electron-Spectrum-20-5m (1)

That change should happen automatically in this case.

### PR DESCRIPTION
**Pull request by gurhar1133**
The undulator seems to be auto updating correctly now

### CODE REVIEW

File: sirepo/package_data/static/js/srw.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ SIREPO.app.factory('srwService', function(activeSection, appDataService, appStat
         });
     };
 
-    self.computeBeamParameters = function() {
+    self.computeBeamParameters = function(callback=null) {
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:180]: `callback` should be named something like `replyHandler`.

File: sirepo/package_data/static/js/srw.js [hunk 2]
```diff
@@ -820,7 +823,10 @@ SIREPO.app.controller('SourceController', function (appState, panelState, srwSer
     $scope.$on('modelChanged', function(e, name) {
         if (name == 'undulator' || name == 'tabulatedUndulator') {
             // make sure the electronBeam.drift is also updated
-            appState.saveQuietly('electronBeamPosition');
+            srwService.computeBeamParameters(() => {
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:826]: I'm concerned about this. The changes are sitting somewhere and then there's an async call which may never return (user closes laptop). The assumption you can just save a random set of changes "some time later" is not a good one. It seems to me that the saveChanges should be happening in the sendStatelessCompute callback, but I could be wrong. However, again, there's no synchronization with the model state at the time of the request and in the response.

File: sirepo/package_data/static/js/srw.js [hunk 3]
```diff
@@ -1462,10 +1468,6 @@ SIREPO.viewLogic('tabulatedUndulatorView', function(appState, panelState, reques
     $scope.whenSelected = updateUndulator;
     $scope.watchFields = [
         ['tabulatedUndulator.undulatorType'], updateUndulator,
-        [
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:1465]: This seems ok. I just don't know enough about the change.

**Review by robnagler — CHANGES_REQUESTED** [review]

File: sirepo/package_data/static/js/srw.js (hunk 3 above)
Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:1465]: We don't need that watchfield anymore since line 823 -
```javascript
 $scope.$on('modelChanged', function(e, name) {
        if (name == 'undulator' || name == 'tabulatedUndulator') {
```
listens and triggers self.computeBeamParameters

File: sirepo/package_data/static/js/srw.js (hunk 2 above)
Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:826]: Not sure I follow here
```
if (replyHandler) {
    replyHandler();
}
```
occurs in the `requestSender.sendStatelessCompute` call. Do you mean something else by saveChanges "should be happening in sendStatelessCompute"?
