### PR TITLE
Fix #2278. Improve NERSC login.

### LINKED ISSUE #2278: NERSC: better UI for login
https://www.sirepo.com/warppba#/dynamics/jrr7Ybt8

The simulation ran fine locally.

Trying to execute at NERSC generated the following error:
image

### PR DESCRIPTION
**Pull request by e-carlin**
This addresses https://github.com/radiasoft/sirepo/issues/2278#issuecomment-633230568.
It makes is clear that the user must press the start button.

Screen Shot 2020-05-26 at 9 21 49 AM

### CODE REVIEW

File: sirepo/package_data/static/js/sirepo-components.js [hunk 1]
```diff
@@ -3184,8 +3184,14 @@ SIREPO.app.directive('sbatchOptions', function(appState) {
                 if  (sbatchLoginStatusService.loggedIn === undefined) {
                     return null;
                 }
-                var s = 'conntected to ' + authState.jobRunModeMap[appState.models[$scope.simState.model].jobRunMode];
-                s = (sbatchLoginStatusService.loggedIn ? '' : 'not ') + s;
+                var s = 'connected to ' +
+                    authState.jobRunModeMap[appState.models[$scope.simState.model].jobRunMode];
+                if (sbatchLoginStatusService.loggedIn) {
+                    s += '. To start press "' + $scope.simState.startButtonLabel() + '"';
```
Comment (e-carlin) [inline sirepo/package_data/static/js/sirepo-components.js:3190]: @robnagler this will appear even when the user has frames and may not want to start a new simulation. Is that a problem?

Also, the text is long. I couldn't come up with anything shorter but open to suggestions.

Comment (robnagler) [reply sirepo/package_data/static/js/sirepo-components.js:3190]: @bruhwiler what say you?
