### PR TITLE
fix #6589: raydata detailed status file

### LINKED ISSUE #6068: raydata: analysis elapsed time
Add the ability to view how long the analysis took for a scan.

### LINKED ISSUE #6589: Detailed status file
The CHX analysis creates a more detailed status that the "cells completed" value. Some notebook cells can take many minutes to complete. The detailed status file is a dictionary of labels to status (in-progress, pending, failed, completed). When running analysis, the current in-progress label should be shown, or possibly a display of all labels and status.

### PR DESCRIPTION
**Pull request by rorour**
fix #6589: raydata detailed status file
fix #6068: raydata analysis elapsed time

### CODE REVIEW

File: sirepo/package_data/static/js/raydata.js [hunk 1]
```diff
@@ -1147,6 +1165,91 @@ SIREPO.app.directive('columnList', function() {
...
+SIREPO.app.directive('scanDetail', function() {
+    return {
+        restrict: 'A',
+        scope: {
+            scan: '<',
+        },
+        template: `
+            <div><strong>Scan Detail</strong></div>
+            <div class="well" style="height: 500px">
+            <div data-ng-if="scan">
```
Comment (moellep) [inline sirepo/package_data/static/js/raydata.js:1177]: The 500px height makes the layout on a laptop so you can't see the search results easily:

x

Ideally, it would be the same height as the search fields to the left, with the option to expand or scroll to see more detail.

File: sirepo/package_data/static/html/raydata-run-analysis.html [hunk 2]
```diff
@@ -1,5 +1,15 @@
...
+      <div class="col-md-7">
+        <div data-advanced-editor-pane="" data-view-name="'runAnalysis'" data-field-def="basic" data-want-buttons="true"></div>
+      </div>
+      <div class="col-md-5">
+        <div data-scan-detail="" data-scan="runAnalysis.raydataService.detailScan"></div>
+      </div>
+      <div class="col-md-12">
+        <div data-model-field="'scans'" data-model-name="'runAnalysis'"></div>
+      </div>
+    </div>
```
Comment (moellep) [inline sirepo/package_data/static/html/raydata-run-analysis.html:13]: Looks good - two other things:

On the Run Analysis tab, when you mouse over the scan table, it should show a "pointer" cursor to indicate you can click on the item. This shouldn't be the behavior on the Queued tab which doesn't have the Scan Detail panel.

When you enter a new search and select "Save", it should clear the currently displayed scan detail info.

**Review by moellep — CHANGES_REQUESTED** [review]

File: sirepo/package_data/static/html/raydata-run-analysis.html (hunk 2 above)
Comment (rorour) [reply sirepo/package_data/static/html/raydata-run-analysis.html:13]: 19b83fcf06f5a7cf22d5b2519a36962ce1026d56

File: sirepo/package_data/static/js/raydata.js (hunk 1 above)
Comment (rorour) [reply sirepo/package_data/static/js/raydata.js:1177]: 19b83fcf06f5a7cf22d5b2519a36962ce1026d56

File: sirepo/package_data/static/js/raydata.js [hunk 3]
```diff
@@ -1147,6 +1165,91 @@ SIREPO.app.directive('columnList', function() {
...
+                for (const k of Object.keys(mostRecentAnalysisDetails())) {
+                    r += k + ': ' + mostRecentAnalysisDetails()[k].status + '\n';
+                }
+                return r;
+            };
+
+            $scope.detailedStatus = () => {
+                return utilities.objectToText($scope.detailedStatusFile());
+            };
+
```
Comment (moellep) [inline sirepo/package_data/static/js/raydata.js:1244]: I made one more change - the status panel was overloaded with scrollbars, including a horizontal scrollbar which was shown but not used:
x

So I removed the inner scrollbars and set the outer scrollbar to "auto":
x2

I also formatted the json in the detail status panel to remove the unneeded syntax.

**Review by moellep — APPROVED** [review]
@rorour the PR looks good. I made one last formatting change to the scan detail panel, and if that looks good to you this PR can be merged.

File: sirepo/package_data/static/js/raydata.js (hunk 3 above)
Comment (rorour) [reply sirepo/package_data/static/js/raydata.js:1244]: Thanks, looks good. Interestingly the horizontal scrollbars weren't showing for me on any browser
