### PR TITLE
Fix #2278. More informative sbatch login and sim frame retrieval afte…

### LINKED ISSUE #2278: NERSC: better UI for login
https://www.sirepo.com/warppba#/dynamics/jrr7Ybt8

The simulation ran fine locally.

Trying to execute at NERSC generated the following error:
image

### PR DESCRIPTION
**Pull request by e-carlin**
…r entering creds.

This fixes 2 issues:
1. Improved sbatch login. There is no more "Error: Please try agin."
It is just the status of the job (ex missing) and there is now alert
text saying "NERSC connection established" or "NERSC no connection"
established after a user enters their credentials.
2. If sim frames are requested and the user doesn't have a NERSC agent
started they will be prompted for the credentials. Upon successfully
entering their credentials the sim frames will be retrieved without
further interaction.

Screen Shot 2020-05-18 at 3 28 28 PM

The `issue/2278-sbatch-login-ui` is based on `issue/2500-select-nersc-queue`. Please review and merge `issue/2500-select-nersc-queue` first.

### CODE REVIEW

File: sirepo/package_data/static/js/srw.js [hunk 1]
```diff
@@ -1903,20 +1903,18 @@ SIREPO.app.directive('simulationStatusPanel', function(appState, beamlineService
...
-                    frameCache.setFrameCount($scope.frameCount);
+                    frameCache.setFrameCount(0);
                     return;
                 }
                 if (data.percentComplete) {
                     $scope.particleNumber = data.particleNumber;
                     $scope.particleCount = data.particleCount;
                 }
                 if (data.frameCount) {
-                    if (data.frameCount != $scope.frameCount) {
```
Comment (e-carlin) [inline sirepo/package_data/static/js/srw.js:1915]: @moellep  I removed $scope.frameCount. I did so because when simState.resetSimulation() was called it only set cacheFrameCount to 0 so data.frameCount === $scope.frameCount and the frames weren't updated. I think using cacheFrameCount has the same effect as scope.frameCount but I'd like you to double check.

Comment (moellep) [reply sirepo/package_data/static/js/srw.js:1915]: Yes, the change looks good. I don't understand what the original code was trying to accomplish.

File: sirepo/job_supervisor.py [hunk 2]
```diff
@@ -710,11 +708,19 @@ def _set_error(op, compute_job_serial):
                 raise
             # There was a timeout getting the run started. Set the
             # error and let the user know. The timeout has destroyed
-            # the op so don't need to in _set_error
-            _set_error(None, c)
+            # the op so don't need to
```
Comment (robnagler) [inline sirepo/job_supervisor.py:711]: unfinished sentence. "need to destroy here."

File: sirepo/job_supervisor.py [hunk 3]
```diff
@@ -710,11 +708,19 @@ def _set_error(op, compute_job_serial):
...
+            _set_error(c, o.internal_error)
             return self._status_reply(req)
-        except Exception:
-            _set_error(o, c)
+        except Exception as e:
+            # _run destroys in the happy path (never got to _run here)
+            o.destroy(cancel=False)
+            if isinstance(e, sirepo.util.SRException) and\
```
Comment (robnagler) [inline sirepo/job_supervisor.py:717]: space before slash

File: sirepo/job_supervisor.py [hunk 4]
```diff
@@ -710,11 +708,19 @@ def _set_error(op, compute_job_serial):
...
+               e.sr_args.params.get('nonJobExc'):
+                self.__db_update(
```
Comment (robnagler) [inline sirepo/job_supervisor.py:719]: One line is fine in this case: self.__db_update(status=s).

Is the update necessary?

File: sirepo/package_data/static/js/sirepo-components.js [hunk 5]
```diff
@@ -3066,34 +3066,38 @@ SIREPO.app.directive('sbatchLoginModal', function() {
...
+                $scope.otp = '';
+                $scope.password = '';
+                $scope.username = '';
+                $scope.sbatchLoginModalForm.$setPristine();
                 $scope.$apply();
             });
 
             function handleResponse(data) {
-                if (data.hasOwnProperty('state') && data.state == 'error') {
+                if (data.state == 'error') {
```
Comment (robnagler) [inline sirepo/package_data/static/js/sirepo-components.js:3097]: why this change?

File: sirepo/package_data/static/js/sirepo-components.js [hunk 6]
```diff
@@ -3066,34 +3066,38 @@ SIREPO.app.directive('sbatchLoginModal', function() {
...
-                $scope.otp = '';
-                $scope.password = '';
-                $scope.username = '';
-                $scope.sbatchLoginModalForm.$setPristine();
                 var r = {'state': 'error', 'error': 'Please try again.'};
                 if (errorResponse) {
                     r = {'state': 'error', 'error': errorResponse};
                 }
-                errorResponse = null;
+                if (authState.sbatchLoginSuccess) {
```
Comment (robnagler) [inline sirepo/package_data/static/js/sirepo-components.js:3083]: I don't like persisting on authState, because it is not returned by the server directly to authState. Please create a new service for this purpose.

File: sirepo/package_data/static/js/sirepo-components.js [hunk 7]
```diff
@@ -3172,10 +3180,22 @@ SIREPO.app.directive('sbatchOptions', function(appState) {
                 appState.watchModelFields($scope, [$scope.simState.model + '.' + e], trimHoursAndCores);
             });
 
+            $scope.connectionStatusMessage = function () {
+                if  (authState.sbatchLoginSuccess === undefined) {
+                    return null;
+                }
+                return authState.jobRunModeMap[appState.models[$scope.simState.model].jobRunMode]
+                    + (authState.sbatchLoginSuccess ? '' : ' no') + ' connection established';
```
Comment (robnagler) [inline sirepo/package_data/static/js/sirepo-components.js:3188]: This is where string files would let us define the message nicely. Mixing presentation and business logic yield wonky error messages. Rather say:

* Connected to v.radia.run
* Not connected to v.radia.run

File: sirepo/package_data/static/js/sirepo-components.js [hunk 8]
```diff
@@ -3172,10 +3180,22 @@ SIREPO.app.directive('sbatchOptions', function(appState) {
...
+            };
+
             $scope.showCoresAndHours = function() {
                 var m = appState.models[$scope.simState.model];
                 return m && m.jobRunMode === 'sbatch';
             };
+
+            $scope.textInfoOrDanger = function () {
+                return authState.sbatchLoginSuccess? 'text-info': 'text-danger';
```
Comment (robnagler) [inline sirepo/package_data/static/js/sirepo-components.js:3197]: space before `:`

File: sirepo/package_data/static/js/sirepo-components.js [hunk 9]
```diff
@@ -3172,10 +3180,22 @@ SIREPO.app.directive('sbatchOptions', function(appState) {
...
+                return authState.jobRunModeMap[appState.models[$scope.simState.model].jobRunMode]
+                    + (authState.sbatchLoginSuccess ? '' : ' no') + ' connection established';
+            };
+
             $scope.showCoresAndHours = function() {
                 var m = appState.models[$scope.simState.model];
                 return m && m.jobRunMode === 'sbatch';
             };
+
+            $scope.textInfoOrDanger = function () {
```
Comment (robnagler) [inline sirepo/package_data/static/js/sirepo-components.js:3196]: Abstract naming: textClass or textStyle.

File: sirepo/package_data/static/js/srw.js [hunk 10]
```diff
@@ -1826,6 +1826,7 @@ SIREPO.app.directive('propagationParametersTable', function(appState) {
     };
 });
 
+
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:1829]: remove extra blank

File: sirepo/package_data/static/js/srw.js [hunk 11]
```diff
@@ -1984,7 +1981,6 @@ SIREPO.app.directive('simulationStatusPanel', function(appState, beamlineService
        },
     };
 });
-
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:1987]: Add blank line

File: sirepo/job_driver/sbatch.py [hunk 12]
```diff
@@ -211,12 +211,13 @@ def _raise_sbatch_login_srexception(self, reason, msg):
         raise util.SRException(
             'sbatchLogin',
             PKDict(
+                host=self.cfg.host,
                 isModal=True,
+                nonJobExc=True,
```
Comment (robnagler) [inline sirepo/job_driver/sbatch.py:216]: Tough name. `isGeneral` matches style of `isModal`. The word "general" can be overused, but "nonJob" seems strange to me.

File: sirepo/job_driver/sbatch.py [hunk 13]
```diff
@@ -211,12 +211,13 @@ def _raise_sbatch_login_srexception(self, reason, msg):
...
                 reason=reason,
+                report=msg.computeModel,
```
Comment (robnagler) [inline sirepo/job_driver/sbatch.py:218]: Since `report` is new, let's leave it `computeModel=msg.computeModel`. It's not a "report" if it is a computeModel.

File: sirepo/job_supervisor.py (hunk 4 above)
Comment (e-carlin) [reply sirepo/job_supervisor.py:719]: Yes here is the scenario:
1) status='missing'
2) user clicks "start new simulation"
3) A new db will be initialized with status='pending'  ([line 680](https://github.com/radiasoft/sirepo/blob/1360b687a319208f17394c88c074bc4033717f5a/sirepo/job_supervisor.py#L680)
4. User must login so an SRException is raised
5. This code is executed setting the status to the old status (missing). Which is the status of the job in the run_dir.
5. The login is succesful and the GUI does a runStatus. The status comes back 'missing' which is correct.

Thinking about this more. Maybe we want to restore the entire db record not just the status? Other fields like computeJobSerial are now incorrect.

File: sirepo/package_data/static/js/sirepo-components.js (hunk 5 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/sirepo-components.js:3097]: Checking hasOwnProperty is unnecessary. If data doesn't have state then `data.state === undefined` and `undefined !=== 'error'` so it has the same effect.

File: sirepo/job_supervisor.py (hunk 4 above)
Comment (robnagler) [reply sirepo/job_supervisor.py:719]: > Maybe we want to restore the entire db record not just the status? 

Yes, this is an interesting problem. The login is happening in connection with a Job, because that's the object we have for connecting to the request. Reality is that we just want to login, and the request has nothing to do with a job. 

Do you think we could handle this request separately so that we don't update the job state at all?

File: sirepo/job_supervisor.py (hunk 2 above)
Comment (e-carlin) [reply sirepo/job_supervisor.py]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/job_supervisor.py (hunk 3 above)
Comment (e-carlin) [reply sirepo/job_supervisor.py]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/sirepo-components.js (hunk 7 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/sirepo-components.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/sirepo-components.js (hunk 8 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/sirepo-components.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/sirepo-components.js (hunk 9 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/sirepo-components.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/srw.js (hunk 10 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/srw.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/job_driver/sbatch.py (hunk 12 above)
Comment (e-carlin) [reply sirepo/job_driver/sbatch.py]: Tough name indeed. isGeneral seems to general (har har har) but it matches isModal and nonJob is no better. Changed https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/job_driver/sbatch.py (hunk 13 above)
Comment (e-carlin) [reply sirepo/job_driver/sbatch.py]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/srw.js (hunk 11 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/srw.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/2c505a1eca579dafbef6921f946a8bc6a642cdc8

File: sirepo/package_data/static/js/sirepo-components.js (hunk 6 above)
Comment (e-carlin) [reply sirepo/package_data/static/js/sirepo-components.js]: https://github.com/radiasoft/sirepo/pull/2523/commits/0cb1cfd8b6624b50c619e9fccc76f0b306fc9d1a

File: sirepo/job_supervisor.py (hunk 4 above)
Comment (e-carlin) [reply sirepo/job_supervisor.py]: https://github.com/radiasoft/sirepo/pull/2523/commits/362eac890cb9e8509e8f41fa1726438eb673fb90

**Comment by e-carlin** [comment]
@robnagler all comments addressed.
