### PR TITLE
Fix #4942: coherent modes errors

### LINKED ISSUE #4942: 20221025 file error in coherent modes on Young's Double Slit Experiment
I looked at srwlib.py, and it is possible that `_file_path=fp_cm` is None. I was running on my machine with one core so maybe it's related. Here's the stack from the run.log:

```txt
Coherent Mode Decomposition done in: 45.415 s
Common Quadratic Terms were added to CMs in: 0.015 s
Traceback (most recent call last):
  File "parameters.py", line 231, in <module>
    main()
  File "parameters.py", line 229, in main
    srwl_bl.SRWLBeamline(_name=v.name).calc_all(v, op)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwl_bl.py", line 3173, in calc_all
    _cm_wfr = lstWfrCM) #OC02072021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwl_bl.py", line 1951, in calc_wfr_emit_prop_me
    _file_bkp = _fbk, _rand_opt = _op_rnd, _file_form = _fform, _n_mpi=_nmm, _n_cm=_ncm) #OC27062021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwlib.py", line 10386, in srwl_wfr_emit_prop_multi_e
    srwl_uti_save_wfr_cm_hdf5(cohModes, None, _awfr=wfrA, _file_path=fp_cm) #OC28062021
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/srwlib.py", line 6828, in srwl_uti_save_wfr_cm_hdf5
    with h5.File(_file_path, 'w') as hf:
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/h5py/_hl/files.py", line 395, in __init__
    name = filename_encode(name)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### PR DESCRIPTION
**Pull request by gurhar1133**
Error is thrown when coherent modes animation has too few cores

### CODE REVIEW

File: sirepo/package_data/static/js/srw.js [hunk 1]
```diff
@@ -2533,6 +2534,20 @@ SIREPO.app.directive('simulationStatusPanel', function(appState, beamlineService
                 return $scope.model == 'coherentModesAnimation';
             }
 
+            function checkRunMode(runMode) {
+                return (runMode == 'sequential') || (runMode == 'parallel');
+            }
+
+            function coherentModesEnoughCores() {
+                var a = appState.models.coherentModesAnimation;
+                if (checkRunMode(a.jobRunMode)) {
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:2543]: The failure can occur in parallel, too. I don't think it should ever be run sequentially.

File: sirepo/package_data/static/js/srw.js [hunk 2]
```diff
@@ -2533,6 +2534,20 @@ SIREPO.app.directive('simulationStatusPanel', function(appState, beamlineService
...
+                    return true;
+                }
+                if (a.sbatchCores < coreMinimum) {
+                    throw new Error(`${a.sbatchCores} cores found, should be > 3 for coherent modes`);
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:2547]: Does this show nicely to the user?

**Review by robnagler — DISMISSED** [review]

File: sirepo/package_data/static/js/srw.js (hunk 2 above)
Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:2547]: Do you want the error coming through in the sim status panel?

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2547]: Yes, because the user should know. On production, they won't see an error if parallel is set, but will see an error if sequential is set. @moellep please correct me if I'm wrong about sequential.

File: sirepo/package_data/static/js/srw.js (hunk 1 above)
Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2543]: Yes. I believe you should get the number of cores correctly in dev.

File: sirepo/package_data/static/js/srw.js (hunk 2 above)
Comment (moellep) [reply sirepo/package_data/static/js/srw.js:2547]: I think it is OK if the error shows up in the page header - it won't be common except on dev. Single-core execution isn't supported for srw - see #4049

Comment (moellep) [reply sirepo/package_data/static/js/srw.js:2547]: Wrong issue number - the correct is #3886 SRW can't run the coherent modes in serial mode on prod anyway.

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2547]: I agree. Let's make this server side and throw a UserAlert.

File: sirepo/package_data/static/js/srw.js (hunk 1 above)
Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:2543]: So '2 cores (SMP)'  should be a failure case?

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js]: Yes.

File: sirepo/package_data/static/js/srw.js [hunk 3]
```diff
@@ -2533,6 +2534,28 @@ SIREPO.app.directive('simulationStatusPanel', function(appState, beamlineService
                 return $scope.model == 'coherentModesAnimation';
             }
 
+            function coherentModesCoresError(cores, minCores) {
+                if (cores < minCores) {
+                    throw new Error(`${cores} cores found, should be > 3 for coherent modes`);
```
Comment (robnagler) [inline sirepo/package_data/static/js/srw.js:2539]: Where does this show up?

Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:2539]: Do you mean where does the error message show up? In the page header.

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2539]: I think this is still the wrong way about it. Since this is an error in configuration, it really should originate from the server and come back as a UserAlert. This way the server protects itself. If there are other users of the API (e.g. tests or bluesky), the server will not produce a reasonable error message.

Comment (moellep) [reply sirepo/package_data/static/js/srw.js:2539]: Yes, I agree it should be on the server and it should throw an exception which would automatically be displayed in the report window. The problem is we don't want it to throw the exception when the code is generated, only when it is run and we can't find the appropriate hook for this on the server because pkcli.srw doesn't use run_background(). Where is the hook in the server to do this check?

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2539]:
```diff
--- a/sirepo/template/srw.py
+++ b/sirepo/template/srw.py
@@ -1052,6 +1052,8 @@ def write_parameters(data, run_dir, is_parallel):
         p = ""
         _export_rsopt_config(data)
     else:
+        if data.report == "coherentModesAnimation":
+            raise sirepo.util.UserAlert("ruh roh!")
         p = _trim(_generate_parameters_file(data, run_dir=run_dir))
     pkio.write_text(
         run_dir.join(template_common.PARAMETERS_PYTHON_FILE),
```

Comment (gurhar1133) [reply sirepo/package_data/static/js/srw.js:2539]: The error from UserAlert doesn't show when in_slurm == True.
eg.
```
Simulation Error: no reply
Elapsed time: 00:00:05
```

 It will only show when not in vagrant/slurm.

Comment (robnagler) [reply sirepo/package_data/static/js/srw.js:2539]: That's a bug. Create an issue. UserAlerts should cascade.

**Comment by moellep** [comment]
Looks great!
